const db = require('./db');

const conteudos = [
  { categoria: 'programacao', titulo: 'Cursos sobre Java', url: 'https://www.skills.google/catalog?keywords=java&locale=pt_BR', descricao: 'Aprenda Java com os cursos oficiais do Google Skills. Java é uma das linguagens mais usadas no mercado de trabalho, especialmente em sistemas corporativos e desenvolvimento Android.', tag: 'Curso', subcategoria: 'Google Skills' },
  { categoria: 'programacao', titulo: 'Cursos sobre Firebase', url: 'https://www.skills.google/catalog?keywords=firebase&locale=pt_BR', descricao: 'Firebase é uma plataforma do Google para criar apps web e mobile com banco de dados em tempo real, autenticação e hospedagem, tudo gerenciado na nuvem.', tag: 'Curso', subcategoria: 'Google Skills' },
  { categoria: 'programacao', titulo: 'Projetos Raspberry Pi (PT-BR)', url: 'https://projects.raspberrypi.org/pt-BR', descricao: 'Plataforma oficial do Raspberry Pi com projetos e tutoriais em português. Ótimo pra quem está começando a programar com eletrônica.', tag: 'Tutoriais', subcategoria: 'Google Skills' },
  { categoria: 'programacao', titulo: 'API do Mercado Pago', url: 'https://www.mercadopago.com.br/developers/pt', descricao: 'Documentação oficial para integrar os serviços de pagamento do Mercado Pago em seus projetos. Muito usado em e-commerces e apps de venda no Brasil.', tag: 'Documentação', subcategoria: 'APIs de Pagamento' },
  { categoria: 'programacao', titulo: 'API do PagBank', url: 'https://developer.pagbank.com.br/docs/apis-pagbank', descricao: 'O PagBank disponibiliza uma série de serviços para que você gerencie cobranças, pagamentos e transferências diretamente nas suas aplicações.', tag: 'Documentação', subcategoria: 'APIs de Pagamento' },
  { categoria: 'banco-dados', titulo: 'Cursos e Certificações — Google Cloud', url: 'https://cloud.google.com/learn?hl=pt-BR', descricao: 'Aprenda sobre banco de dados, infraestrutura e serviços na nuvem com o Google Cloud. Ótimo para quem quer uma certificação reconhecida no mercado.', tag: 'Certificação', subcategoria: 'Google Cloud' },
  { categoria: 'banco-dados', titulo: 'Google Cloud Free Tier', url: 'https://cloud.google.com/free?hl=pt-br', descricao: 'O Google Cloud oferece um nível gratuito com vários serviços e produtos para você praticar e aprender sem gastar nada. Ideal para estudantes.', tag: 'Gratuito', subcategoria: 'Google Cloud' },
  { categoria: 'eletronica', titulo: 'Raspberry Pi para Casa', url: 'https://www.raspberrypi.com/for-home/', descricao: 'O Raspberry Pi é um computador de baixo custo que cabe na palma da mão. Nessa página você encontra tudo sobre como usá-lo em casa para projetos criativos.', tag: 'Oficial', subcategoria: 'Raspberry Pi — Referências Oficiais' },
  { categoria: 'eletronica', titulo: 'Tutoriais Oficiais', url: 'https://www.raspberrypi.com/tutorials/', descricao: 'Guias oficiais com passo a passo para criar projetos com o Raspberry Pi. Desde iniciantes até projetos avançados como servidores e automação.', tag: 'Tutorial', subcategoria: 'Raspberry Pi — Referências Oficiais' },
  { categoria: 'eletronica', titulo: 'Primeiros Passos com o Raspberry Pi Pico', url: 'https://projects.raspberrypi.org/en/projects/getting-started-with-the-pico', descricao: 'O Raspberry Pi Pico é um microcontrolador pequeno e barato, ótimo para projetos de eletrônica. Esse tutorial ensina do zero como programá-lo.', tag: 'Microcontrolador', subcategoria: 'Raspberry Pi — Referências Oficiais' },
  { categoria: 'eletronica', titulo: 'Espelho Inteligente', url: 'https://www.raspberrypi.com/tutorials/how-to-build-a-super-slim-smart-mirror/', descricao: 'Tutorial oficial do Raspberry Pi para construir um espelho inteligente que mostra informações como hora, clima e notícias na sua superfície.', tag: 'Projeto', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'Instalando o Magic Mirror do Zero', url: 'https://www.youtube.com/watch?v=moCOf6vRQyA', descricao: 'Vídeo em português mostrando como instalar e configurar o aplicativo Magic Mirror no Raspberry Pi do zero, passo a passo.', tag: 'Vídeo', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'Segredos do Espelho Inteligente', url: 'https://www.youtube.com/watch?v=NsLmnxv4ii8', descricao: 'Super dicas para personalizar e turbinar seu espelho inteligente com módulos extras como calendário, previsão do tempo e muito mais.', tag: 'Vídeo', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'Android Auto no Raspberry Pi', url: 'https://www.youtube.com/watch?v=lgUQih_rSjw', descricao: 'Aprenda como integrar o Android Auto em um projeto com Raspberry Pi, transformando qualquer carro num veículo conectado.', tag: 'Vídeo', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'Raspberry Pi + Plex — Servidor de Mídia', url: 'https://www.ionos.com/digitalguide/server/configuration/raspberry-pi-plex/', descricao: 'Aprenda a transformar seu Raspberry Pi em um servidor de mídia pessoal usando o Plex, podendo acessar seus filmes e músicas de qualquer lugar.', tag: 'Tutorial', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'Central Multimídia com Raspberry Pi', url: 'https://www.makerhero.com/guia/raspberry-pi/central-de-midia-raspberry-pi/', descricao: 'Guia completo da MakerHero para transformar seu Raspberry Pi em uma central de entretenimento para a sua casa.', tag: 'Guia', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'Raspberry Pi Zero 2 W — Apresentação', url: 'https://www.youtube.com/watch?v=U_GVtfht9S0', descricao: 'Conheça o Raspberry Pi Zero 2 W, o computador de placa única mais compacto e acessível da linha Raspberry Pi.', tag: 'Vídeo', subcategoria: 'Projetos Práticos' },
  { categoria: 'eletronica', titulo: 'MakerHero', url: 'https://www.makerhero.com/', descricao: 'Loja brasileira especializada em produtos para makers: Raspberry Pi, Arduino, sensores, robôs e tudo que você precisa para seus projetos.', tag: 'Loja', subcategoria: 'Onde Comprar' },
  { categoria: 'eletronica', titulo: 'RoboCore — Raspberry Pi', url: 'https://www.robocore.net/raspberry-pi', descricao: 'A RoboCore é outra loja brasileira com uma grande variedade de componentes e kits para projetos com Raspberry Pi e eletrônica em geral.', tag: 'Loja', subcategoria: 'Onde Comprar' },
  { categoria: 'eletronica', titulo: 'Raspberry Pi Pico 2 W', url: 'https://www.makerhero.com/produto/raspberry-pi-pico-2-w/', descricao: 'O Raspberry Pi Pico 2 W é um microcontrolador com chip ARM Cortex-M33, Wi-Fi e Bluetooth integrados. Perfeito para projetos de IoT e automação.', tag: 'Produto', subcategoria: 'Onde Comprar' },
  { categoria: 'treinamentos', titulo: 'Google Skills — Catálogo Completo', url: 'https://www.skills.google/catalog?locale=pt_BR', descricao: 'Todos os treinamentos e certificações do Google reunidos em um só lugar, disponíveis em português. Ótima plataforma gratuita para estudantes de TI.', tag: 'Plataforma', subcategoria: 'Google Skills' },
  { categoria: 'treinamentos', titulo: 'Google Cloud — Cursos e Certificações', url: 'https://cloud.google.com/learn?hl=pt-BR', descricao: 'Aprenda e se certifique nos serviços de nuvem do Google. Ótimo para quem quer trabalhar com infraestrutura e tecnologia em larga escala.', tag: 'Cloud', subcategoria: 'Google Skills' },
  { categoria: 'treinamentos', titulo: 'Empresa Júnior Senac', url: 'https://www.linkedin.com/in/ejsenac/', descricao: 'A Empresa Júnior do Senac São Paulo é uma ótima oportunidade para ganhar experiência prática em projetos reais ainda durante o curso.', tag: 'LinkedIn', subcategoria: 'Senac' },
  { categoria: 'projetos-especiais', titulo: 'Como Construir um Espelho Inteligente', url: 'https://www.raspberrypi.com/tutorials/how-to-build-a-super-slim-smart-mirror/', descricao: 'Tutorial passo a passo do site oficial do Raspberry Pi para montar um espelho inteligente que exibe informações úteis na sua superfície.', tag: 'Tutorial', subcategoria: 'Espelho Inteligente — Magic Mirror' },
  { categoria: 'projetos-especiais', titulo: 'Instalando o Magic Mirror do Zero', url: 'https://www.youtube.com/watch?v=moCOf6vRQyA', descricao: 'Vídeo completo em português sobre como instalar e configurar o aplicativo Magic Mirror no Raspberry Pi do absoluto zero.', tag: 'Vídeo', subcategoria: 'Espelho Inteligente — Magic Mirror' },
  { categoria: 'projetos-especiais', titulo: 'Segredos do Espelho Inteligente', url: 'https://www.youtube.com/watch?v=NsLmnxv4ii8', descricao: 'Super dicas para personalizar seu espelho inteligente com módulos de calendário, clima, notícias e muito mais.', tag: 'Vídeo', subcategoria: 'Espelho Inteligente — Magic Mirror' },
  { categoria: 'projetos-especiais', titulo: 'Raspberry Pi + Plex', url: 'https://www.ionos.com/digitalguide/server/configuration/raspberry-pi-plex/', descricao: 'Monte um servidor de mídia pessoal transformando seu Raspberry Pi em um Plex server. Acesse seus filmes e músicas de qualquer dispositivo.', tag: 'Tutorial', subcategoria: 'Servidor de Mídia' },
  { categoria: 'projetos-especiais', titulo: 'Central Multimídia com Raspberry Pi', url: 'https://www.makerhero.com/guia/raspberry-pi/central-de-midia-raspberry-pi/', descricao: 'Guia da MakerHero para transformar seu Raspberry Pi em uma central de entretenimento completa para sua casa.', tag: 'Guia', subcategoria: 'Servidor de Mídia' },
  { categoria: 'meus-projetos', titulo: 'Atividade Final — 3° ano T.I', url: 'https://enzocros.github.io/ATIVIDADE-FINAL/', descricao: 'Meu primeiro site, desenvolvido no 3° ano do técnico em T.I. Uma página de apresentação pessoal com minhas soft e hard skills, feita com HTML e CSS do zero.', tag: 'Primeiro Site', subcategoria: 'Projetos Acadêmicos' },
];

const sql = 'INSERT INTO conteudos (categoria, titulo, url, descricao, tag, subcategoria) VALUES (?, ?, ?, ?, ?, ?)';

let count = 0;
conteudos.forEach(c => {
  db.query(sql, [c.categoria, c.titulo, c.url, c.descricao, c.tag, c.subcategoria], (err) => {
    if (err) {
      console.error(`Erro ao inserir "${c.titulo}":`, err.message);
    } else {
      console.log(`✅ Inserido: ${c.titulo}`);
    }
    count++;
    if (count === conteudos.length) {
      console.log('\nPronto! Todos os conteúdos inseridos.');
      db.end();
    }
  });
});